name: Build Test

on:
  push:
    branches: [ "master", "workflow" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
    - name: 0. Prerequisities
      run: sudo apt-get install -y git build-essential autoconf cmake libglu1-mesa-dev libgtk-3-dev libdbus-1-dev
    - name: 1. Cloning the repository
      uses: actions/checkout@v3
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}
    - name: Determine dependency hash
      id: dephash
      run: echo dephash=$(git rev-parse HEAD:deps) >> $GITHUB_OUTPUT
    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: deps/build/destdir
        key: dependencycache-${{ runner.os }}-${{ steps.dephash.outputs.dephash }}
    - name: Cache Download Files
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      id: cache-download
      uses: actions/cache@v3
      with:
        path: deps/download
        key: downloadcache-${{ runner.os }}-${{ github.run_id }}
        restore-keys: |
          downloadcache-${{ runner.os }}
    - name: 2. Building dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        cd deps
        mkdir -p build
        cd build
        cmake .. -DDEP_WX_GTK3=ON -DDEP_DOWNLOAD_DIR=$(pwd)/../download
        make
        cd ../..
    - name: 3. Building PrusaSlicer
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        mkdir build
        cd build
        cmake .. -DSLIC3R_STATIC=1 -DSLIC3R_GTK=3 -DSLIC3R_PCH=OFF -DSLIC3R_GUI=OFF -DCMAKE_PREFIX_PATH=$(pwd)/../deps/build/destdir/usr/local
        make -j $(nproc)
